sudo: false
language: node_js
node_js:
  - 12
cache: npm
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: public
